# Generated by Django 5.2.16 on 2026-07-10 19:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.CharField(max_length=63, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$', 'Use lowercase letters, digits and hyphens (no leading/trailing hyphen).')])),
                ('name', models.CharField(max_length=200)),
                ('default_head_scripts', models.TextField(blank=True, default='', help_text='Managed scripts injected into <head> of every published page.')),
                ('default_body_scripts', models.TextField(blank=True, default='', help_text='Managed scripts injected before </body> of every published page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('tls_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='sites.site')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
