# Generated by Django 5.2.16 on 2026-07-13 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('editable_id', models.CharField(help_text='data-editable-id of the <form> node this configures.', max_length=200)),
                ('name', models.CharField(default='Lead form', max_length=200)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=1000)),
                ('submit_mode', models.CharField(choices=[('proxy', 'Server-side proxy')], default='proxy', max_length=16)),
                ('success_url', models.URLField(blank=True, default='', help_text='External success URL (if no Page).', max_length=1000)),
                ('gate_redirect_on_success', models.BooleanField(default=False, help_text='Off (default): store + redirect immediately, forward async. On: wait for the webhook to succeed before redirecting.')),
                ('field_map', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='pages.page')),
                ('success_page', models.ForeignKey(blank=True, help_text='Thank-you Page in this Site to send visitors to on success.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.page')),
            ],
            options={
                'ordering': ['editable_id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('webhook_status', models.CharField(choices=[('skipped', 'No webhook configured'), ('pending', 'Pending'), ('succeeded', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(fields=('page', 'editable_id'), name='unique_form_per_page'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['form', '-created_at'], name='forms_submi_form_id_09a0f5_idx'),
        ),
    ]
