# Generated by Django 5.2.16 on 2026-07-10 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_url', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(max_length=100)),
                ('bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
